grid_map_filters:
  ros__parameters:

    input_topic: /elevation_map_raw
    output_topic: /filtered_map

    filters:
      filter1:
        name: buffer_normalizer
        type: gridMapFilters/BufferNormalizerFilter


      filter2:  # Fill holes in the map with inpainting.
        name: inpaint
        type: gridMapCv/InpaintFilter
        params:
          input_layer: elevation
          output_layer: elevation_inpainted
          radius: 0.5

      filter3:  # Reduce noise with a radial blurring filter.
        name: mean_in_radius
        type: gridMapFilters/MeanInRadiusFilter
        params:
          input_layer: elevation_inpainted
          output_layer: elevation_smooth
          radius: 0.5
          
      filter4:  # Compute surface normals.
        name: surface_normals
        type: gridMapFilters/NormalVectorsFilter
        params:
          input_layer: elevation_smooth
          output_layers_prefix: normal_vectors_
          radius: 1.0
          normal_vector_positive_axis: z

      filter5:  # Compute slope from surface normal.
        name: slope
        type: gridMapFilters/MathExpressionFilter
        params:
          output_layer: slope
          expression: acos(normal_vectors_z)














          
      # filter5:  # Add a color layer for visualization based on the surface normal.
            #   name: normal_color_map
            #   type: gridMapFilters/NormalColorMapFilter
            #   params:
            #     input_layers_prefix: normal_vectors_
            #     output_layer: normal_color

      # filter6:  # Compute slope from surface normal.
      #   name: slope
      #   type: gridMapFilters/SlidingWindowMathExpressionFilter
      #   params:
      #     input_layer: normal_vectors_z
      #     output_layer: slope
      #     expression: atan2(sqrt(1 - normal_vectors_z^2) / normal_vectors_z)
      #     compute_empty_cells: false
      #     edge_handling: crop # options: inside, crop, empty, mean
      #     window_size: 3

          
      # filter7:  # Compute roughness as absolute difference from map to smoothened map.
      #   name: roughness
      #   type: gridMapFilters/MathExpressionFilter
      #   params:
      #     output_layer: roughness
      #     expression: abs(elevation_inpainted - elevation_smooth)

      # filter8:
      #   name: slope_color
      #   type: gridMapFilters/ColorMapFilter
      #   params:
      #     min/color: [0.0, 0.0, 1.0]  # Bleu en RGB (normalisé entre 0 et 1)
      #     max/color: [1.0, 0.0, 0.0]  # Rouge en RGB (normalisé entre 0 et 1)
      #     min/value: -1.0
      #     max/value: 1.0
      #     input_layer: slope
      #     output_layer: slope_color
      
      # filter9:
      #   name: elevation_smooth_color
      #   type: gridMapFilters/ColorMapFilter
      #   params:
      #     min/color: [0.0, 0.0, 1.0]  # Bleu en RGB (normalisé entre 0 et 1)
      #     max/color: [1.0, 0.0, 0.0]  # Rouge en RGB (normalisé entre 0 et 1)
      #     min/value: -2.0
      #     max/value: 2.0
      #     input_layer: elevation_smooth
      #     output_layer: elevation_smooth_color