floor_normal_filters:
  ros__parameters:

    input_topic: /grid_map
    output_topic: /floor_normal

    filters:
      filter1:
        name: buffer_normalizer
        type: gridMapFilters/BufferNormalizerFilter

      # filter2: # Duplicate layer.
      #   name: duplicate
      #   type: gridMapFilters/DuplicationFilter
      #   params:
      #     input_layer: ...
      #     output_layer: ...

      # filter2:  # Delete color layer.
      #   name: delete_original_layers
      #   type: gridMapFilters/DeletionFilter
      #   params: 
      #     layers: [color] # List of layers.

      filter2:  # Fill holes in the map with inpainting.
        name: inpaint
        type: gridMapCv/InpaintFilter
        params:
          input_layer: elevation
          output_layer: elevation_inpainted
          radius: 0.08


      filter3:  # Compute surface normals.
        name: surface_normals
        type: gridMapFilters/NormalVectorsFilter
        params:
          input_layer: elevation_inpainted
          output_layers_prefix: normal_vectors_
          radius: 0.08
          normal_vector_positive_axis: z

      filter4:  # Add a color layer for visualization based on the surface normal.
        name: normal_color_map
        type: gridMapFilters/NormalColorMapFilter
        params:
          input_layers_prefix: normal_vectors_
          output_layer: normal_color

