octomap_to_gridmap_demo:
  ros__parameters:
    octomap_service_topic: "/octomap_binary"
    min_z: -50.0
    max_z: 50.0

grid_map_visualization:
  ros__parameters:
    grid_map_topic: /grid_map
    grid_map_visualizations: [surface_normals,elevation_points,map_region,traversability_grid] 
    surface_normals:
      type: vectors
      params:
        layer_prefix: normal_vectors_
        position_layer: elevation
        scale: 0.06
        line_width: 0.005
        color: 15600153 # red
    elevation_points:
      type: point_cloud
      params:
        layer: elevation
    map_region:
      type: map_region
      params:
        color: 3289650
        line_width: 0.1
    traversability_grid:
      type: occupancy_grid
      params:
        layer: slope
        data_min: 0.0
        data_max: 1.57


 